# Generated by Django 3.2.7 on 2023-08-16 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rut', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 16, 0, 9, 5, 519083))),
                ('deleted_at', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rut', models.CharField(max_length=9)),
                ('entry', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=9)),
                ('partnership', models.ManyToManyField(related_name='parnets', to='partnership.Partnership')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rut', models.CharField(max_length=9)),
                ('capacity', models.CharField(choices=[('abrir una cuenta corriente', 'abrir una cuenta corriente'), ('firmar cheques', 'firmar cheques'), ('firmar contratos', 'firmar contratos')], default='nominativas', max_length=30)),
                ('partnership', models.ManyToManyField(related_name='managers', to='partnership.Partnership')),
            ],
        ),
    ]
