# Generated by Django 3.2.7 on 2023-08-16 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0002_auto_20230816_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.CharField(max_length=129),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partnership',
            field=models.ManyToManyField(related_name='partners', to='partnership.Partnership'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 16, 1, 4, 10, 829351)),
        ),
    ]
